# Generated by Django 5.2.7 on 2025-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bottle/images/')),
                ('material', models.CharField(choices=[('P', 'Plastic'), ('A', 'Aluminium')], max_length=20)),
                ('sku', models.CharField(max_length=16)),
            ],
        ),
    ]
