# Generated by Django 5.2.7 on 2025-10-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='bottle/images/')),
                ('material', models.CharField(choices=[('plastic', 'Plastic'), ('aluminium', 'Aluminium')], max_length=20)),
            ],
        ),
    ]
