# Generated by Django 5.2.7 on 2025-10-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bottle/images/'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='material',
            field=models.CharField(choices=[('P', 'Plastic'), ('A', 'Aluminium')], max_length=20),
        ),
    ]
