# Generated by Django 5.2.7 on 2025-10-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_alter_bottle_image_alter_bottle_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='image',
        ),
    ]
