# Generated by Django 5.2.7 on 2025-10-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0003_remove_bottle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bottle/images/'),
        ),
    ]
